### ISSUE TITLE
如果用户全程只点击一个选项，狂点

### ISSUE THREAD

**Issue by jskyzero** [HeskeyBaozi/album-match-music#1]
中间歌曲可能会出现在等待的时候就开始播放然后最后在DisplayCorrectSong还会出一个System.NullReferenceException:“Object reference not set to an instance of an object.”

哇社会是真的险恶，我本来对着dalao的代码逻辑拿去就用，想着dalao的逻辑怎么可能会出错呢

**Comment by HeskeyBaozi** [comment]
啊。我到你宿舍来吧。
